newfies/dnc/urls.py
#
# Newfies-Dialer License
# http://www.newfies-dialer.org
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (C) 2011-2015 Star2Billing S.L.
#
# The primary maintainer of this project is
# Arezqui Belaid <info@star2billing.com>
#

from django.conf.urls import patterns


urlpatterns = patterns('dnc.views',
                       # DNC urls
                       (r'^module/dnc_list/$', 'dnc_list'),
                       (r'^module/dnc_list/add/$', 'dnc_add'),
                       (r'^module/dnc_list/contact_count/$', 'get_dnc_contact_count'),
                       (r'^module/dnc_list/del/(.+)/$', 'dnc_del'),
                       (r'^module/dnc_list/(.+)/$', 'dnc_change'),

                       # DNC Contacts urls
                       (r'^module/dnc_contact/$', 'dnc_contact_list'),
                       (r'^module/dnc_contact/add/$', 'dnc_contact_add'),
                       (r'^module/dnc_contact_import/$', 'dnc_contact_import'),
                       (r'^module/dnc_contact/export/$', 'dnc_contact_export'),
                       (r'^module/dnc_contact/export_view/$', 'dnc_contact_export_view'),
                       (r'^module/dnc_contact/del/(.+)/$', 'dnc_contact_del'),
                       (r'^module/dnc_contact/(.+)/$', 'dnc_contact_change'),
                       )

newfies/mod_sms/urls.py
#
# Newfies-Dialer License
# http://www.newfies-dialer.org
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (C) 2011-2012 Star2Billing S.L.
#
# The primary maintainer of this project is
# Arezqui Belaid <info@star2billing.com>
#

from django.conf.urls import patterns

urlpatterns = patterns('mod_sms.views',

                       # SMS Campaign urls
                       (r'^sms_dashboard/$', 'sms_dashboard'),
                       (r'^sms_campaign/$', 'sms_campaign_list'),
                       (r'^sms_campaign/add/$', 'sms_campaign_add'),
                       (r'^sms_campaign/del/(.+)/$', 'sms_campaign_del'),
                       (r'^sms_campaign/duplicate/(.+)/$', 'sms_campaign_duplicate'),
                       (r'^sms_campaign/text_message/(.+)/$', 'sms_campaign_text_message'),

                       # SMS Campaign Actions (start|stop|pause|abort) for customer UI
                       (r'^sms_campaign/update_sms_campaign_status_cust/(\d*)/(\d*)/$',
                        'update_sms_campaign_status_cust'),
                       (r'^sms_campaign/(.+)/$', 'sms_campaign_change'),

                       # SMS Campaign Actions (start|stop|pause|abort) for Admin UI
                       (r'^update_sms_campaign_status_admin/(\d*)/(\d*)/$',
                        'update_sms_campaign_status_admin'),

                       # SMS Report urls
                       (r'^sms_report/$', 'sms_report'),
                       (r'^export_sms_report/$', 'export_sms_report'),
                       )

newfies/newfies_dialer/urls.py
#
# Newfies-Dialer License
# http://www.newfies-dialer.org
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (C) 2011-2015 Star2Billing S.L.
#
# The primary maintainer of this project is
# Arezqui Belaid <info@star2billing.com>
#
from django.conf.urls import handler404, handler500, \
    include, patterns, url
from django.conf import settings
from apirest.urls import urlpatterns as urlpatterns_apirest
from agent.api_urls import urlpatterns as urlpatterns_agent_apirest
from appointment.urls import urlpatterns as urlpatterns_appointment
from frontend.urls import urlpatterns as urlpatterns_frontend
from dialer_contact.urls import urlpatterns as urlpatterns_dialer_contact
from dialer_campaign.urls import urlpatterns as urlpatterns_dialer_campaign
from dialer_cdr.urls import urlpatterns as urlpatterns_dialer_cdr
from dnc.urls import urlpatterns as urlpatterns_dnc
from user_profile.urls import urlpatterns as urlpatterns_user_profile
from survey.urls import urlpatterns as urlpatterns_survey
from dialer_audio.urls import urlpatterns as urlpatterns_dialer_audio
from frontend_notification.urls import urlpatterns as urlpatterns_frontend_notification
# from agent.urls import urlpatterns as urlpatterns_agent
# from callcenter.urls import urlpatterns as urlpatterns_callcenter
from mod_sms.urls import urlpatterns as urlpatterns_mod_sms
from dajaxice.core import dajaxice_autodiscover, dajaxice_config
from django.contrib import admin
import os


admin.autodiscover()
dajaxice_autodiscover()

js_info_dict = {
    'domain': 'djangojs',
    'packages': ('dialer_campaign',
                 'user_profile',
                 'survey',
                 'audiofield'),
}

urlpatterns = patterns('',
                       (r'^logout/$', 'frontend.views.logout_view'),
                       (r'^admin/', include(admin.site.urls)),
                       (r'^i18n/', include('django.conf.urls.i18n')),
                       (r'^jsi18n/$', 'django.views.i18n.javascript_catalog', js_info_dict),
                       (r'^admin_tools/', include('admin_tools.urls')),
                       (r'^static/(?P<path>.*)$', 'django.views.static.serve',
                        {'document_root': settings.STATIC_ROOT}),
                       # (r'^sentry/', include('sentry.web.urls')),
                       # (r'^%s/' % settings.DAJAXICE_MEDIA_PREFIX, include('dajaxice.urls')),
                       url(dajaxice_config.dajaxice_url, include('dajaxice.urls')),
                       (r'^accounts/', include('registration.backends.default.urls')),
                       )

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += patterns('', url(r'^__debug__/', include(debug_toolbar.urls)),)

urlpatterns += urlpatterns_apirest
urlpatterns += urlpatterns_agent_apirest
urlpatterns += urlpatterns_frontend
urlpatterns += urlpatterns_dialer_contact
urlpatterns += urlpatterns_dialer_campaign
urlpatterns += urlpatterns_dialer_cdr
urlpatterns += urlpatterns_dnc
urlpatterns += urlpatterns_user_profile
urlpatterns += urlpatterns_survey
urlpatterns += urlpatterns_dialer_audio
urlpatterns += urlpatterns_frontend_notification
# urlpatterns += urlpatterns_agent
# urlpatterns += urlpatterns_callcenter
urlpatterns += urlpatterns_appointment
urlpatterns += urlpatterns_mod_sms

urlpatterns += patterns('',
                        (r'^%s/(?P<path>.*)$' % settings.MEDIA_URL.strip(os.sep),
                         'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
                        )


handler404 = 'urls.custom_404_view'
handler500 = 'urls.custom_500_view'


def custom_404_view(request, template_name='404.html'):
    """404 error handler which includes ``request`` in the context.

    Templates: `404.html`
    Context: None
    """
    from django.template import Context, loader
    from django.http import HttpResponseServerError

    t = loader.get_template('404.html')  # Need to create a 404.html template.
    return HttpResponseServerError(t.render(Context({
        'request': request,
    })))


def custom_500_view(request, template_name='500.html'):
    """500 error handler which includes ``request`` in the context.

    Templates: `500.html`
    Context: None
    """
    from django.template import Context, loader
    from django.http import HttpResponseServerError

    t = loader.get_template('500.html')  # Need to create a 500.html template.
    return HttpResponseServerError(t.render(Context({
        'request': request,
    })))

newfies/mod_sms/models.py
#
# Newfies-Dialer License
# http://www.newfies-dialer.org
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (C) 2011-2012 Star2Billing S.L.
#
# The primary maintainer of this project is
# Arezqui Belaid <info@star2billing.com>
#

from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.utils.timezone import now
from django.core.urlresolvers import reverse
from django.core.cache import cache
from django.db.models.signals import post_save
from django.utils.encoding import force_unicode
from dateutil.relativedelta import relativedelta
from dialer_contact.models import Phonebook, Contact
from dialer_contact.constants import CONTACT_STATUS
from sms.models import Message
from sms.models import Gateway
from constants import SMS_CAMPAIGN_STATUS, SMS_SUBSCRIBER_STATUS
from django_lets_go.intermediate_model_base_class import Model
from django_lets_go.common_functions import get_unique_code
from datetime import datetime
from django.utils.timezone import utc


def build_kwargs_runnning_smscampaign():
    """Return kwargs configured to filter running SMS Campaign"""
    kwargs = {}
    kwargs['status'] = SMS_CAMPAIGN_STATUS.START
    tday = datetime.utcnow().replace(tzinfo=utc)
    kwargs['startingdate__lte'] = datetime(
        tday.year, tday.month, tday.day, tday.hour,
        tday.minute, tday.second, tday.microsecond).replace(tzinfo=utc)
    kwargs['expirationdate__gte'] = datetime(
        tday.year, tday.month, tday.day, tday.hour,
        tday.minute, tday.second, tday.microsecond).replace(tzinfo=utc)

    # s_time = "%s:%s:%s" % (str(tday.hour), str(tday.minute), str(tday.second))
    # Fix for timezone
    today = datetime.now()
    kwargs['daily_start_time__lte'] = today.strftime('%H:%M:%S')
    kwargs['daily_stop_time__gte'] = today.strftime('%H:%M:%S')

    # weekday status 1 - YES
    # self.model._meta.get_field(tday.strftime("%A").lower()).value()
    kwargs[tday.strftime("%A").lower()] = 1
    return kwargs


class SMSCampaignManager(models.Manager):

    """SMSCampaign Manager"""

    def get_running_sms_campaign(self):
        """Return all the active smscampaigns which will be running based on
        the expiry date, the daily start/stop time and days of the week"""

        kwargs = build_kwargs_runnning_smscampaign()
        return SMSCampaign.objects.filter(**kwargs)

    def get_expired_sms_campaign(self):
        """Return all the smscampaigns which are expired or going to expire
         based on the expiry date but status is not 'END'"""
        kwargs = {}
        kwargs['expirationdate__lte'] = datetime.utcnow().replace(tzinfo=utc)
        return SMSCampaign.objects.filter(**kwargs).exclude(status=SMS_CAMPAIGN_STATUS.END)


def set_campaign_code():
    return get_unique_code(length=5)


def set_expirationdate():
    return datetime.utcnow().replace(tzinfo=utc) + relativedelta(days=+1)


class SMSCampaign(Model):

    """This defines the SMSCampaign

    **Attributes**:

        * ``campaign_code`` - Auto-generated campaign code to identify the campaign
        * ``name`` - Campaign name
        * ``description`` - Description about the Campaign
        * ``status`` - Campaign status
        * ``callerid`` - Caller ID
        * ``startingdate`` - Starting date of the Campaign
        * ``expirationdate`` - Expiry date of the Campaign
        * ``daily_start_time`` - Start time
        * ``daily_stop_time`` - End time
        * ``week_day_setting`` (monday, tuesday, wednesday, thursday, friday, \
        saturday, sunday)
        * ``frequency`` - Frequency, speed of the campaign. number of calls/min
        * ``maxretry`` - Max retry allowed per user
        * ``intervalretry`` - Time to wait between retries in seconds
        * ``sms_gateway`` - Gateway to transport the SMS
        * ``extra_data`` - Additional data to pass to the application

    **Relationships**:

        * ``content_type`` - Defines the application (``voice_app`` or ``survey``) \
        to use when the call is established on the A-Leg

        * ``object_id`` - Defines the object of content_type application

        * ``content_object`` - Used to define the Voice App or the Survey with generic ForeignKey

        * ``phonebook`` - Many-To-Many relationship to the Phonebook model.

        * ``user`` - Foreign key relationship to the a User model. \
        Each campaign assigned to a User

    **Name of DB table**: sms_campaign
    """
    campaign_code = models.CharField(unique=True, max_length=20, blank=True,
                                     verbose_name=_("SMS campaign code"),
                                     help_text=_('this code is auto-generated by the platform, \
                                     this is used to identify the campaign'),
                                     default=set_campaign_code)

    name = models.CharField(max_length=100, verbose_name=_('name'))
    description = models.TextField(verbose_name=_('description'), blank=True,
                                   null=True, help_text=_("campaign description"))
    user = models.ForeignKey('auth.User', related_name='SMSCampaign owner')
    status = models.IntegerField(choices=list(SMS_CAMPAIGN_STATUS),
                                 default=SMS_CAMPAIGN_STATUS.PAUSE, verbose_name=_("status"))
    callerid = models.CharField(max_length=80, blank=True,
                                verbose_name=_("Caller ID Number"),
                                help_text=_("outbound Caller ID"))
    # General Starting & Stopping date
    startingdate = models.DateTimeField(default=now, verbose_name=_('start'))
    stoppeddate = models.DateTimeField(default=set_expirationdate, verbose_name=_('stopped'))
    expirationdate = models.DateTimeField(default=set_expirationdate, verbose_name=_('finish'))

    # Per Day Starting & Stopping Time
    daily_start_time = models.TimeField(default='00:00:00')
    daily_stop_time = models.TimeField(default='23:59:59')
    monday = models.BooleanField(default=True, verbose_name=_('monday'))
    tuesday = models.BooleanField(default=True, verbose_name=_('tuesday'))
    wednesday = models.BooleanField(default=True, verbose_name=_('wednesday'))
    thursday = models.BooleanField(default=True, verbose_name=_('thursday'))
    friday = models.BooleanField(default=True, verbose_name=_('friday'))
    saturday = models.BooleanField(default=True, verbose_name=_('saturday'))
    sunday = models.BooleanField(default=True, verbose_name=_('sunday'))
    # Campaign Settings
    frequency = models.IntegerField(default='10', blank=True, null=True,
                                    verbose_name=_('frequency'),
                                    help_text=_("SMS per minute"))

    maxretry = models.IntegerField(default='0', blank=True, null=True,
                                   verbose_name=_('max retries'),
                                   help_text=_("maximum retries per contact"))
    intervalretry = models.IntegerField(default='300', blank=True, null=True,
                                        verbose_name=_('time between Retries'),
                                        help_text=_("time delay in seconds before retrying contact"))

    sms_gateway = models.ForeignKey(Gateway, verbose_name=_("sms gateway"),
                                    related_name="SMS Gateway",
                                    help_text=_("select SMS gateway"))
    text_message = models.TextField(verbose_name=_('text Message'), blank=False, null=False)

    extra_data = models.CharField(max_length=120, blank=True,
                                  verbose_name=_("extra parameters"),
                                  help_text=_("additional application parameters."))

    created_date = models.DateTimeField(auto_now_add=True, verbose_name='Date')
    updated_date = models.DateTimeField(auto_now=True)

    phonebook = models.ManyToManyField(Phonebook, blank=True, null=True)

    imported_phonebook = models.CharField(max_length=500, default='',
                                          verbose_name=_('list of imported phonebook'))
    totalcontact = models.IntegerField(default=0, blank=True, null=True,
                                       verbose_name=_('total contact'),
                                       help_text=_("total contact for this campaign"))

    objects = SMSCampaignManager()

    def __unicode__(self):
        return u"%s" % (self.name)

    class Meta:
        permissions = (
            ("view_smscampaign", _('can see SMS campaign')),
            ("view_sms_dashboard", _('can see SMS campaign dashboard'))
        )
        db_table = u'sms_campaign'
        verbose_name = _("SMS campaign")
        verbose_name_plural = _("SMS campaigns")

    def update_sms_campaign_status(self):
        """Update the sms_campaign's status

        For example,
        If campaign is active, you can change status to 'Pause' or 'Stop'
        """
        # active - 1 | pause - 2 | abort - 3 | stop - 4
        if self.status == SMS_CAMPAIGN_STATUS.START:
            return "<a href='%s'>Pause</a> | <a href='%s'>Abort</a> | <a href='%s'>Stop</a>" % (
                reverse('mod_sms.views.update_sms_campaign_status_admin', args=[self.pk, SMS_CAMPAIGN_STATUS.PAUSE]),
                reverse('mod_sms.views.update_sms_campaign_status_admin', args=[self.pk, SMS_CAMPAIGN_STATUS.ABORT]),
                reverse('mod_sms.views.update_sms_campaign_status_admin', args=[self.pk, SMS_CAMPAIGN_STATUS.END]))

        if self.status == SMS_CAMPAIGN_STATUS.PAUSE:
            return "<a href='%s'>Start</a> | <a href='%s'>Abort</a> | <a href='%s'>Stop</a>" % (
                reverse('mod_sms.views.update_sms_campaign_status_admin', args=[self.pk, SMS_CAMPAIGN_STATUS.START]),

newfies/mod_sms/templates/mod_sms/change.html
{% extends "frontend/master.html" %}
{% load i18n crispy_forms_tags %}

{% block extra_files %}
    {{ form.media }}
{% endblock %}

{% block content_header %}
    <h1>{{ action|capfirst }} {% trans "SMS" %} {% trans "campaign"|title %}
        <small>{% trans "set SMS campaign parameters"|capfirst %}</small>
    </h1>
{% endblock %}

{% block content %}
    {% crispy form form.helper %}
{% endblock %}

newfies/mod_sms/templates/mod_sms/list.html
{% extends "frontend/master.html" %}
{% load i18n pagination_tags common_tags mod_sms_tags crispy_forms_tags %}

{% block extra_header %}
    <link href="{{ STATIC_URL }}/vis/dist/vis.css" rel="stylesheet" type="text/css" />
    <script src="{{ STATIC_URL }}/vis/dist/vis.js"></script>
{% endblock %}

{% block content_header %}
    <h1>{% trans "SMS" %} {% trans "campaign"|title %} <small>{% trans "list, add and edit SMS campaigns"|capfirst %}</small></h1>
{% endblock %}

{% block content %}
<div id="form_collapse" class="collapse">
    {% crispy form form.helper %}
</div>

{% include "frontend/common_search_toggle_button.html" %}
<div>&nbsp;</div>
<div class="row">
    <div class="col-md-12">
        <div class="btn-group">
            <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
            {% trans "action"|capfirst %} <span class="caret"></span>
            </button>
            <ul class="dropdown-menu" role="menu">
                {% if perms.mod_sms.delete_smscampaign %}
                    <li><a href="#" onclick="delete_button()">{% trans "delete selected"|capfirst %}</a></li>
                {% endif %}
                <li>
                    <a href="#" onclick="sms_campaign_stop_button()">{% trans "stop selected"|title %}</a>
                </li>
            </ul>
        </div>
        {% if perms.mod_sms.add_smscampaign %}
            <button type="button" class="btn btn-info" onclick="add_button()">
                <i class="fa fa-plus"></i> {% trans "add"|title %}
            </button>
        {% endif %}
    </div>
</div>

<br/>

<div class="row">
    <div class="col-md-12">
        <form method="POST" action="del/0/" enctype="multipart/form-data" id="ListForm">{% csrf_token %}
            <div class="table-responsive">
                <table class="table table-striped table-bordered table-condensed">
                    <thead>
                    <tr>
                        <th><input type="checkbox" onclick="toggleChecked(this.checked)"></th>
                        <th>{% sort_link SMS_CAMPAIGN_COLUMN_NAME.key col_name_with_order.id %}</th>
                        <th>{% sort_link SMS_CAMPAIGN_COLUMN_NAME.name col_name_with_order.name %}</th>
                        <th>{% sort_link SMS_CAMPAIGN_COLUMN_NAME.start_date col_name_with_order.startingdate %}</th>
                        <th>{% sort_link SMS_CAMPAIGN_COLUMN_NAME.sms_gateway col_name_with_order.gateway %}</th>
                        <th>{% sort_link SMS_CAMPAIGN_COLUMN_NAME.totalcontact col_name_with_order.totalcontact %}</th>
                        <th>{% sort_link SMS_CAMPAIGN_COLUMN_NAME.status col_name_with_order.status %}</th>
                        <th>{{ SMS_CAMPAIGN_COLUMN_NAME.action }}</th>
                    </tr>
                    </thead>
                    {% if smscampaign_list %}
                        {% autopaginate smscampaign_list newfies_page_size %}
                        {% for row in smscampaign_list %}
                            <tr>
                                <td><input type="checkbox" name="select" class="checkbox" value="{{ row.id }}" /></td>
                                <td>{{ row.campaign_code }}</td>
                                <td>{{ row.name }}</td>
                                <td>{{ row.startingdate }}</td>
                                <td>{{ row.sms_gateway }}</td>
                                <td>{{ row.totalcontact }}</td>
                                <td>{% get_sms_campaign_status_url row.id row.status %} - {{ row.status|get_sms_campaign_status|safe }}
                                </td>
                                <td>
                                    {% if perms.mod_sms.change_smscampaign %}
                                        <a href="{{ row.id }}/" title="{% trans 'update sms campaign'|capfirst %}"><i class="fa fa-edit"></i></a>
                                    {% endif %}
                                    {% if perms.mod_sms.delete_smscampaign %}
                                        <a id="id_delete_confirm" href="del/{{ row.id }}/" title="{% trans 'delete sms campaign'|capfirst %}"><i class="fa fa-trash-o"></i></a>
                                    {% endif %}
                                    {{ row.id|create_duplicate_sms_campaign|safe }}

                                    {{ row.id|get_sms_campaign_textmessage|safe }}
                                </td>
                            </tr>
                        {% endfor %}
                    {% else %}
                        <tr>
                            <td colspan="9" align="center">
                                {% trans "no records found"|title %}
                            </td>
                        </tr>
                    {% endif %}
                </table>
            </div>
            <div class="text-right">
                {% trans "total"|title %} : {{ total_campaign }}
            </div>
            {% if smscampaign_list %}
                {% paginate %}
            {% endif %}
        </form>
    </div>
</div>
<!--sms-campaign-duplicate modal-->
<script type="text/javascript" charset="utf-8">
    $(".sms-campaign-duplicate").on('click', function(e) {
        var url = $(this).attr('url');
        var modal_id = $(this).attr('data-controls-modal');
        $("#" + modal_id).load(url);
    });
</script>
<!-- modal content-->
<div id="sms-campaign-duplicate" class="modal fade" role="dialog" aria-labelledby="add_duplicate_sms_campaign"></div>

<!--sms-campaign-textmessage modal-->
<script type="text/javascript" charset="utf-8">
    $(".sms-campaign-textmessage").on('click', function(e) {
        var url = $(this).attr('url');
        var modal_id = $(this).attr('data-controls-modal');
        $("#" + modal_id).load(url);
    });
</script>
<!-- modal content-->
<div id="sms-campaign-textmessage" class="modal fade" role="dialog" aria-labelledby="get_sms_campaign_textmessage"></div>

<hr/>

<!-- Timeline-->
<div id="mytimeline"></div>

  <script type="text/javascript">
    // DOM element where the Timeline will be attached
    var container = document.getElementById('mytimeline');

    // Create a DataSet with data (enables two way data binding)
    var data = new vis.DataSet([
    {% for row in smscampaign_list %}
      {id: {{ row.id }}, content: '{{ row.name }}', start: '{{ row.startingdate|date:"Y-m-d H:i:s" }}', end: '{{ row.stoppeddate|date:"Y-m-d H:i:s" }}'},
    {% endfor %}
    ]);

    // Configuration for the Timeline
    var options = {};

    // Create a Timeline
    var timeline = new vis.Timeline(container, data, options);
  </script>


{% endblock %}

newfies/mod_sms/templates/mod_sms/sms_campaign_duplicate.html
{% extends "frontend/master.html" %}
{% load i18n common_tags crispy_forms_tags %}

{% block header_files %}
{% endblock %}

{% block extra_files %}
{% endblock %}

{% block row_fluid %}
{% endblock %}

{% block header %}
{% endblock %}

{% block menu %}
{% endblock %}

{% block container %}

    {% block content %}
        {% if err_msg %}
            {% include "frontend/extra_modal_header.html" %}
            {% include "frontend/extra_modal_footer.html" %}
            <script type="text/javascript" charset="utf-8">
                $(window).load(function(){
                    $('#sms-duplicate-campaign').modal('show');
                });
                function back_to(){
                    var url = '/sms_campaign/';
                    $(location).attr('href', url);
                }
            </script>
            <!-- modal content-->
            <div class="modal fade" id="sms-duplicate-campaign" role="dialog" aria-labelledby="add_duplicate_sms_campaign" data-backdrop="static">
        {% endif %}
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <a id="id_close_x" class="close" data-dismiss="modal" {% if err_msg %}onclick="back_to();"{% endif %}>&times;</a>
                    <h3>{% trans "sms"|upper %} {% trans "campaign"|title %}
                        <small></small>
                    </h3>
                </div>
                <form role="form" method="POST" action="/sms_campaign/duplicate/{{ sms_campaign_id }}/" enctype="multipart/form-data" id="update_form">
                    <div class="modal-body">
                        {% crispy form form.helper %}
                    </div>

                    <div class="modal-footer" align="right">
                        <button type="submit" class="btn btn-primary" id="id_add" name="add" value="{% trans 'save'|title %}">
                            <i class="fa fa-save"></i> {% trans "save"|title %}
                        </button>
                        <button id="id_close" type="button" class="btn btn-default" data-dismiss="modal" {% if err_msg %}onclick="back_to();"{% endif %}>{% trans "close"|title %}</button>
                    </div>
                </form>
            </div>
        </div>
    {% if err_msg %}
        </div>
    {% endif %}

    {% endblock %}

{% endblock %}

{% block footer %}
{% endblock %}

newfies/mod_sms/templates/mod_sms/sms_campaign_text_message.html
{% extends "frontend/master.html" %}
{% load i18n common_tags %}

{% block header_files %}
{% endblock %}

{% block extra_files %}
{% endblock %}

{% block row_fluid %}
{% endblock %}

{% block header %}
{% endblock %}

{% block menu %}
{% endblock %}

{% block container %}

    {% block content %}
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <a id="id_close_x" class="close" data-dismiss="modal" >&times;</a>
                    <h3>{% trans "text message"|title %}
                        <small></small>
                    </h3>
                </div>

                <div class="modal-body">
                    {{ sms_campaign.text_message }}
                </div>

                <div class="modal-footer" align="right">
                    <button id="id_close" type="button" class="btn btn-default" data-dismiss="modal">{% trans "close"|title %}</button>
                </div>
            </div>
        </div>
    {% endblock %}

{% endblock %}

{% block footer %}
{% endblock %}