newfies/dialer_contact/urls.py
#
# Newfies-Dialer License
# http://www.newfies-dialer.org
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (C) 2011-2015 Star2Billing S.L.
#
# The primary maintainer of this project is
# Arezqui Belaid <info@star2billing.com>
#
from django.conf.urls import patterns


urlpatterns = patterns('dialer_contact.views',
                       # Phonebook urls
                       (r'^phonebook/$', 'phonebook_list'),
                       (r'^phonebook/add/$', 'phonebook_add'),
                       (r'^phonebook/contact_count/$', 'get_contact_count'),
                       (r'^phonebook/del/(.+)/$', 'phonebook_del'),
                       (r'^phonebook/(.+)/$', 'phonebook_change'),

                       # Contacts urls
                       (r'^contact/$', 'contact_list'),
                       (r'^contact/add/$', 'contact_add'),
                       (r'^contact_import/$', 'contact_import'),
                       (r'^contact/del/(.+)/$', 'contact_del'),
                       (r'^contact/(.+)/$', 'contact_change'),
                       )

newfies/dnc/urls.py
#
# Newfies-Dialer License
# http://www.newfies-dialer.org
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (C) 2011-2015 Star2Billing S.L.
#
# The primary maintainer of this project is
# Arezqui Belaid <info@star2billing.com>
#

from django.conf.urls import patterns


urlpatterns = patterns('dnc.views',
                       # DNC urls
                       (r'^module/dnc_list/$', 'dnc_list'),
                       (r'^module/dnc_list/add/$', 'dnc_add'),
                       (r'^module/dnc_list/contact_count/$', 'get_dnc_contact_count'),
                       (r'^module/dnc_list/del/(.+)/$', 'dnc_del'),
                       (r'^module/dnc_list/(.+)/$', 'dnc_change'),

                       # DNC Contacts urls
                       (r'^module/dnc_contact/$', 'dnc_contact_list'),
                       (r'^module/dnc_contact/add/$', 'dnc_contact_add'),
                       (r'^module/dnc_contact_import/$', 'dnc_contact_import'),
                       (r'^module/dnc_contact/export/$', 'dnc_contact_export'),
                       (r'^module/dnc_contact/export_view/$', 'dnc_contact_export_view'),
                       (r'^module/dnc_contact/del/(.+)/$', 'dnc_contact_del'),
                       (r'^module/dnc_contact/(.+)/$', 'dnc_contact_change'),
                       )

newfies/newfies_dialer/urls.py
#
# Newfies-Dialer License
# http://www.newfies-dialer.org
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (C) 2011-2015 Star2Billing S.L.
#
# The primary maintainer of this project is
# Arezqui Belaid <info@star2billing.com>
#
from django.conf.urls import handler404, handler500, \
    include, patterns, url
from django.conf import settings
from apirest.urls import urlpatterns as urlpatterns_apirest
from agent.api_urls import urlpatterns as urlpatterns_agent_apirest
from appointment.urls import urlpatterns as urlpatterns_appointment
from frontend.urls import urlpatterns as urlpatterns_frontend
from dialer_contact.urls import urlpatterns as urlpatterns_dialer_contact
from dialer_campaign.urls import urlpatterns as urlpatterns_dialer_campaign
from dialer_cdr.urls import urlpatterns as urlpatterns_dialer_cdr
from dnc.urls import urlpatterns as urlpatterns_dnc
from user_profile.urls import urlpatterns as urlpatterns_user_profile
from survey.urls import urlpatterns as urlpatterns_survey
from dialer_audio.urls import urlpatterns as urlpatterns_dialer_audio
from frontend_notification.urls import urlpatterns as urlpatterns_frontend_notification
# from agent.urls import urlpatterns as urlpatterns_agent
# from callcenter.urls import urlpatterns as urlpatterns_callcenter
from mod_sms.urls import urlpatterns as urlpatterns_mod_sms
from dajaxice.core import dajaxice_autodiscover, dajaxice_config
from django.contrib import admin
import os


admin.autodiscover()
dajaxice_autodiscover()

js_info_dict = {
    'domain': 'djangojs',
    'packages': ('dialer_campaign',
                 'user_profile',
                 'survey',
                 'audiofield'),
}

urlpatterns = patterns('',
                       (r'^logout/$', 'frontend.views.logout_view'),
                       (r'^admin/', include(admin.site.urls)),
                       (r'^i18n/', include('django.conf.urls.i18n')),
                       (r'^jsi18n/$', 'django.views.i18n.javascript_catalog', js_info_dict),
                       (r'^admin_tools/', include('admin_tools.urls')),
                       (r'^static/(?P<path>.*)$', 'django.views.static.serve',
                        {'document_root': settings.STATIC_ROOT}),
                       # (r'^sentry/', include('sentry.web.urls')),
                       # (r'^%s/' % settings.DAJAXICE_MEDIA_PREFIX, include('dajaxice.urls')),
                       url(dajaxice_config.dajaxice_url, include('dajaxice.urls')),
                       (r'^accounts/', include('registration.backends.default.urls')),
                       )

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += patterns('', url(r'^__debug__/', include(debug_toolbar.urls)),)

urlpatterns += urlpatterns_apirest
urlpatterns += urlpatterns_agent_apirest
urlpatterns += urlpatterns_frontend
urlpatterns += urlpatterns_dialer_contact
urlpatterns += urlpatterns_dialer_campaign
urlpatterns += urlpatterns_dialer_cdr
urlpatterns += urlpatterns_dnc
urlpatterns += urlpatterns_user_profile
urlpatterns += urlpatterns_survey
urlpatterns += urlpatterns_dialer_audio
urlpatterns += urlpatterns_frontend_notification
# urlpatterns += urlpatterns_agent
# urlpatterns += urlpatterns_callcenter
urlpatterns += urlpatterns_appointment
urlpatterns += urlpatterns_mod_sms

urlpatterns += patterns('',
                        (r'^%s/(?P<path>.*)$' % settings.MEDIA_URL.strip(os.sep),
                         'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
                        )


handler404 = 'urls.custom_404_view'
handler500 = 'urls.custom_500_view'


def custom_404_view(request, template_name='404.html'):
    """404 error handler which includes ``request`` in the context.

    Templates: `404.html`
    Context: None
    """
    from django.template import Context, loader
    from django.http import HttpResponseServerError

    t = loader.get_template('404.html')  # Need to create a 404.html template.
    return HttpResponseServerError(t.render(Context({
        'request': request,
    })))


def custom_500_view(request, template_name='500.html'):
    """500 error handler which includes ``request`` in the context.

    Templates: `500.html`
    Context: None
    """
    from django.template import Context, loader
    from django.http import HttpResponseServerError

    t = loader.get_template('500.html')  # Need to create a 500.html template.
    return HttpResponseServerError(t.render(Context({
        'request': request,
    })))

newfies/dialer_contact/models.py
#
# Newfies-Dialer License
# http://www.newfies-dialer.org
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (C) 2011-2015 Star2Billing S.L.
#
# The primary maintainer of this project is
# Arezqui Belaid <info@star2billing.com>
#

from django.db import models
from django.utils.translation import ugettext_lazy as _
from django_countries.fields import CountryField
from django_lets_go.intermediate_model_base_class import Model
from dialer_contact.constants import CONTACT_STATUS
import jsonfield
import re


class Phonebook(Model):

    """This defines the Phonebook

    **Attributes**:

        * ``name`` - phonebook name.
        * ``description`` - description about the phonebook.

    **Relationships**:

        * ``user`` - Foreign key relationship to the User model.\
        Each phonebook is assigned to a User

    **Name of DB table**: dialer_phonebook
    """
    name = models.CharField(max_length=90, verbose_name=_('name'))
    description = models.TextField(null=True, blank=True, help_text=_("phonebook notes"))
    user = models.ForeignKey('auth.User', related_name='Phonebook owner')
    created_date = models.DateTimeField(auto_now_add=True, verbose_name=_('date'))
    updated_date = models.DateTimeField(auto_now=True)

    class Meta:
        permissions = (
            ("view_phonebook", _('can see phonebook')),
        )
        db_table = u'dialer_phonebook'
        verbose_name = _("phonebook")
        verbose_name_plural = _("phonebooks")

    def __unicode__(self):
        return u"%s" % self.name

    def phonebook_contacts(self):
        """This will return a count of the contacts in the phonebook"""
        return Contact.objects.filter(phonebook=self.id).count()
    phonebook_contacts.allow_tags = True
    phonebook_contacts.short_description = _('contacts')


class Contact(Model):

    """This defines the Contact

    **Attributes**:

        * ``contact`` - Contact no
        * ``last_name`` - Contact's last name
        * ``first_name`` - Contact's first name
        * ``email`` - Contact's e-mail address
        * ``city`` - city name
        * ``description`` - description about a Contact
        * ``status`` - contact status
        * ``additional_vars`` - Additional variables

    **Relationships**:

        * ``phonebook`` - Foreign key relationship to the Phonebook model.\
        Each contact mapped with a phonebook
        * ``country`` - Foreign key relationship to the Country model.\
        Each contact mapped with a country

    **Name of DB table**: dialer_contact
    """
    phonebook = models.ForeignKey(Phonebook, verbose_name=_('phonebook'))
    contact = models.CharField(max_length=90, verbose_name=_('contact number'))
    status = models.IntegerField(choices=list(CONTACT_STATUS), default=CONTACT_STATUS.ACTIVE,
                                 verbose_name=_("status"), blank=True, null=True)
    last_name = models.CharField(max_length=120, blank=True, null=True, verbose_name=_('last name'))
    first_name = models.CharField(max_length=120, blank=True, null=True, verbose_name=_('first name'))
    email = models.EmailField(blank=True, null=True, verbose_name=_('email'))
    address = models.CharField(max_length=250, null=True, blank=True, verbose_name=_("address"))
    city = models.CharField(max_length=120, blank=True, null=True, verbose_name=_('city'))
    state = models.CharField(max_length=120, blank=True, null=True, verbose_name=_('state'))
    country = CountryField(blank=True, null=True, verbose_name=_('country'))
    unit_number = models.CharField(max_length=50, blank=True, null=True, verbose_name=_("unit number"))
    additional_vars = jsonfield.JSONField(
        null=True, blank=True, verbose_name=_('additional parameters (JSON)'),
        help_text=_("enter the list of parameters in JSON format, e.g. {\"age\": \"32\"}"))
    description = models.TextField(null=True, blank=True, verbose_name=_("notes"))
    created_date = models.DateTimeField(auto_now_add=True, verbose_name=_('date'))
    updated_date = models.DateTimeField(auto_now=True)

    class Meta:
        permissions = (
            ("view_contact", _('can see contact')),
        )
        db_table = u'dialer_contact'
        verbose_name = _("contact")
        verbose_name_plural = _("contacts")

    def __unicode__(self):
        # this will be used by duplicate_contact
        return u"%s" % (self.contact)

    def contact_name(self):
        """Return Contact Name"""
        return u"%s %s" % (self.first_name, self.last_name)

    def replace_tag(self, text):
        """
        Replace tag by contact values.
        This function will replace all the following tags:

            {last_name}
            {first_name}
            {email}
            {country}
            {city}
            {phone_number}

        as well as, get additional_vars, and replace json tags
        """
        # text = text.encode('utf-8')
        taglist = {
            'last_name': self.last_name,
            'first_name': self.first_name,
            'email': self.email,
            'country': self.country,
            'city': self.city,
            'phone_number': self.contact,
        }
        if self.additional_vars:
            for index in self.additional_vars:
                taglist[index] = self.additional_vars[index]

        for ind in taglist:
            text = text.replace('{' + ind + '}', str(taglist[ind]))

        # replace the tags not found
        text = re.sub('{(\w+)}', '', text)
        return text

    contact_name.allow_tags = True
    contact_name.short_description = _('name')

newfies/dialer_contact/templates/dialer_contact/phonebook/change.html
{% extends "frontend/master.html" %}
{% load i18n crispy_forms_tags %}

{% block content_header %}
    <h1>{{ action|capfirst }} {% trans "phonebook"|title %}
        <small>{% trans "contacts are stored in phonebooks"|capfirst %}</small>
    </h1>
{% endblock %}

{% block content %}
    {% crispy form form.helper %}
{% endblock %}

newfies/dialer_contact/templates/dialer_contact/phonebook/list.html
{% extends "frontend/master.html" %}
{% load i18n pagination_tags common_tags %}

{% block content_header %}
    <h1>{% trans "phonebook"|title %} <small>{% trans "list, add and edit phonebooks"|capfirst %}</small></h1>
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-12">
        <div class="btn-group">
            <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
            {% trans "action"|capfirst %} <span class="caret"></span>
            </button>
            <ul class="dropdown-menu" role="menu">
                {% if perms.dialer_contact.delete_phonebook %}
                    <li><a href="#" onclick="delete_button()">{% trans "delete selected"|title %}</a></li>
                {% endif %}
            </ul>
        </div>
        {% if perms.dialer_contact.add_phonebook %}
            <button type="button" class="btn btn-info" onclick="add_button()">
                <i class="fa fa-plus"></i> {% trans "add"|title %}
            </button>
        {% endif %}
    </div>
</div>
<br/>
<div class="row">
    <div class="col-md-12">
        <form method="POST" action="del/0/" enctype="multipart/form-data" id="ListForm">{% csrf_token %}
            <div class="table-responsive">
                <table class="table table-striped table-bordered table-condensed">
                    <thead>
                    <tr>
                        <th><input type="checkbox" onclick="toggleChecked(this.checked)"></th>
                        <th>{% sort_link PHONEBOOK_COLUMN_NAME.id|capfirst col_name_with_order.id %}</th>
                        <th>{% sort_link PHONEBOOK_COLUMN_NAME.name|capfirst col_name_with_order.name %}</th>
                        <th>{{ PHONEBOOK_COLUMN_NAME.description|capfirst }}</th>
                        <th>{% sort_link PHONEBOOK_COLUMN_NAME.date|capfirst col_name_with_order.updated_date %}</th>
                        <th>{{ PHONEBOOK_COLUMN_NAME.contacts|capfirst }}</th>
                        <th>{% trans 'action'|capfirst %}</th>
                    </tr>
                    </thead>
                    {% if phonebook_list %}
                        {% autopaginate phonebook_list newfies_page_size %}
                        {% for row in phonebook_list %}
                            <tr>
                                <td><input type="checkbox" name="select" class="checkbox" value="{{ row.id }}" /></td>
                                <td>{{ row.id }}</td>
                                <td>{{ row.name }}</td>
                                <td>{{ row.description }}</td>
                                <td>{{ row.updated_date }}</td>
                                <td>{{ row.contact_count }}</td>
                                <td>
                                    {% if perms.dialer_contact.change_phonebook %}
                                        <a href="{{ row.id }}/" title="{% trans 'update phonebook'|title %}"><i class="fa fa-edit"></i></a>
                                    {% endif %}
                                    {% if perms.dialer_contact.delete_phonebook %}
                                        <a id="id_phonebook_delete_confirm-{{ row.id }}" onclick="return get_alert_msg_for_phonebook({{ row.id }});" href="del/{{ row.id }}/" title="{% trans 'delete phonebook'|title %}"><i class="fa fa-trash-o"></i></a>
                                    {% endif %}
                                </td>
                            </tr>
                        {% endfor %}
                    {% else %}
                        <tr>
                            <td colspan="8" align="center">
                                {% trans "no records found"|title %}
                            </td>
                        </tr>
                    {% endif %}
                </table>
            </div>
            <div class="text-right">
                {% trans "total"|title %} : {{ total_phonebook }}
            </div>
            {% if phonebook_list %}
                {% paginate %}
            {% endif %}
        </form>
    </div>
</div>
{% endblock %}